# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExpandFoundation' do

pod 'AFNetworking', '~> 3.1.0'
pod 'MBProgressHUD', '~> 0.9'
pod 'Reachability', '~> 3.2'

end
