# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

inhibit_all_warnings! #消除第三方库警告
#use_frameworks!

target 'ExpandFoundation' do

pod 'AFNetworking', '~> 3.1.0'
pod 'MBProgressHUD', '~> 0.9'
pod 'Reachability', '~> 3.2'

end
